# Generated by Django 3.2 on 2022-11-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justsayhi', '0002_auto_20221107_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='authed_user_access_token',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='authed_user_id',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
